#**Numpy Dizi Verilerine Erişim**

In [1]:
import numpy as np

Liste oluşturuyoruz.

In [2]:
numbers = np.array([1, 2, 3, 4, 5, 10, 15, 20, 50 , 75])
#5. dizine erişiyoruz.
result = numbers[5]
#yazdıralım
print(result)

10


Belli aralıktaki değerler yazdırılır. [x,y) sınırlarında verilir.

In [3]:
result2 = numbers[2:5]
print(result2)

[3 4 5]


Belli bir yerden ihtibaren:

In [4]:
result = numbers[3:]
print(result)

[ 4  5 10 15 20 50 75]


Tüm dizi:

In [5]:
result = numbers[::]

In [6]:
print(result)

[ 1  2  3  4  5 10 15 20 50 75]


Listeyi ters çeviriyoruz.

In [7]:
result = numbers[::-1]
result2 = numbers[::-2]

print(result)
print(result2)

[75 50 20 15 10  5  4  3  2  1]
[75 20 10  4  2]


##**2 Boyutlu diziler üzerindeki çalışmalarım:**

In [16]:
numbers2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(numbers2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


N. satırı yazdıralım.

In [9]:
print(numbers2[0])

[1 2 3 4 5]


i. satırın j. indexini yazdıralım.

In [11]:
print(numbers2[1,3])

9


Tüm dizi içinden j. kolonu yazdıralım.

In [12]:
columnJ = numbers2[:,4]
print(columnJ)

[ 5 10 15]


In [13]:
columnJtoM = numbers2[:,1:4]
print(columnJtoM)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


Bu sefer row yani satırları yazdıracağız. ':' işaretinin soluna istediğimiz satır numarasını yazıyoruz.

In [14]:
rowN = numbers2[-1,:]
#en son satırı yazdırıyıoruz
print(rowN)

[11 12 13 14 15]


Dizimizin i. satırından m. satırına kadar, j. kolonundan m. kolonuna kadar yeni bir dizi olusturun.

In [15]:
newArray = numbers2[1:3,1:4]

print(newArray)

[[ 7  8  9]
 [12 13 14]]


İlk dizimizi atadığımız ikinci dizimizde değişiklik yapacağız. Şaşırtıcı bir şekilde ilk dizi de değişiyor.


In [17]:
arr1 = np.arange(0, 10)
arr2 = arr1

arr2[0] = 100

print(arr1)
print(arr2)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


Burada referans kopyalama yaptık.

arr1 ve arr2 aynı adreste idi. Şimdi de farklı adreste olacak şekilde arr1 dizisini kopyalayalım.

In [18]:
arr2 = arr1.copy()
arr2[0] = 200
print(arr1)
print(arr2)

[100   1   2   3   4   5   6   7   8   9]
[200   1   2   3   4   5   6   7   8   9]


Görüldüğü gibi ilk listede güncellenme yapılmadı.