<a href="https://colab.research.google.com/github/myz21/BILTEK-AI/blob/master/(4)Numpy%C4%B0%C5%9Flemler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)


Belli aralıkta, elemanları rastgele tam sayılar olacak şekilde, 6 elemanlı iki dizi oluşturduk.

In [3]:
print(numbers1)
print(numbers2)

[24 94 70 91 71 42]
[57 79 86 49 38 55]


Vektörlerimizi (dizilerimizi) toplayalım.

In [4]:
result = numbers1 + numbers2

print(result)

[ 81 173 156 140 109  97]


Diziden belli sayıyı çıkaralım.

In [5]:
result = numbers1 - 10
print(result)

[14 84 60 81 61 32]


İki dizinin farkı:

In [6]:
result = numbers1 - numbers2

print(result)


[-33  15 -16  42  33 -13]


In [8]:
result  = numbers1 * numbers2

print(result)

[1368 7426 6020 4459 2698 2310]


Dizinin sinüs, karekök, logaritma değerini alıp bunları ayrı listeler içine yazdıralım

In [9]:
result = np.sin(numbers1)
print(result)
result = np.sqrt(numbers1)
print(result)
result = np.log(numbers1)
print(result)

[-0.90557836 -0.24525199  0.77389068  0.10598751  0.95105465 -0.91652155]
[4.89897949 9.69535971 8.36660027 9.53939201 8.42614977 6.4807407 ]
[3.17805383 4.54329478 4.24849524 4.51085951 4.26267988 3.73766962]


6x1 olan dizilerden 2x3'lük 2 x 3 matris oluşturduk.

In [10]:
multiNumbers1 = numbers1.reshape(2,3)
multiNumbers2 = numbers2.reshape(2,3)
print("multiNumbers1")
print(multiNumbers1)
print("multiNumbers2")
print(multiNumbers2)

multiNumbers1
[[24 94 70]
 [91 71 42]]
multiNumbers2
[[57 79 86]
 [49 38 55]]


Dizileri alt alta birbirleriyle birleştirelim. Yeni yığın dizimizi yazdıralım.

In [12]:
result = np.vstack((multiNumbers1,multiNumbers2))
print("Stack vertically.")
print(result)

Stack vertically.
[[24 94 70]
 [91 71 42]
 [57 79 86]
 [49 38 55]]


Dizielri yatay olarak birleştirelim.

In [13]:
result = np.hstack((multiNumbers1,multiNumbers2))
print("Stack horizontally.")
print(result)

Stack horizontally.
[[24 94 70 57 79 86]
 [91 71 42 49 38 55]]


Dizinin elemanlarının her birinin belli bir değerden büyük olup olmadığını kontrol ediyoruz.

In [14]:
#Boolean dizisi oluşturulacak.
result = numbers2 > 50
print(result)

[ True  True  True False False  True]


Dizi elemanlarının belli bir işlemi sağlayıp sağlamadığını kontrol ediyoruz. Yeni bir boolean dizisi daha :)


In [15]:
result = numbers2 % 2 == 0
print(result)

[False False  True False  True False]


Hangi elemanların bu koşulları sağladığını bulacağız.

In [17]:
result = numbers2 % 2 == 0
print(numbers2[result])

[86 38]
